pipeline:
  identifier: Build_SyedAzhar234_python_harness_1702249831539
  name: Build python-harness
  orgIdentifier: default
  projectIdentifier: pythontest
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1702249818199
        repoName: SyedAzhar234/python-harness
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  identifier: build_python_app
                  name: Build Python App
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      python -m pip install --upgrade pip
                      pip install  pytest
                      if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
