pipeline:
  identifier: Build_SyedAzhar234_python_harness_1702249831539
  name: Build python-harness
  orgIdentifier: default
  projectIdentifier: pythontest
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1702249818199
        repoName: SyedAzhar234/python-harness
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      repo: hello/world
                      tags: latest
                  timeout: ""
                  type: Plugin
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
